[package]
name = "leptoaster-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.7.3", features = ["csr"] }
leptoaster = { version = "0.2.1", features = ["csr"] }
console_error_panic_hook = "0.1.7"
